### ISSUE TITLE
Ignore bundle entries with  {"mode" : "outcome"}

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#107]
The test suite is throwing warnings like:

    Assertion Failed: No codings in Observation.code match http://hl7.org/fhir/us/argonaut/ValueSet/argo-vital-signs.

and

... but it's unclear which Observation is the "offending" one. It looks like the test suite is getting confused when it received a bundle with 20 Observations (entry.mode="match") and an OperationOutcome (entry.mode="outcome"), by looking for a `code` on the OperationOutcome. We should filter out any entries where mode != "match".

**Comment by erikwiffin** [comment]
I don't think we need to do that. The `get_resources` method in argonaut.py takes a `filter_type` param and only returns resources that match it (https://github.com/sync-for-science/test-suite/blob/master/features/steps/argonaut.py#L39).

It looks like this is actually a bug introduced in https://github.com/sync-for-science/test-suite/commit/9c48c62fe086cdf84f8c9f0986809e2c8c2b735d. We're filtering codings based on system, and none of the codings match "http://hl7.org/fhir/us/argonaut/ValueSet/argo-vital-signs", which they shouldn't, because their systems should be "http://loinc.org".

I think I need to change the two "is bound to" tests to filter by codes that validate against the provided valueset URL, and then raises an exception if nothing is left. Basically turn the existing two steps into one.

**Comment by jmandel** [comment]
Ok! Note that this same issue also causes errors like "no 'patient' found" even when the regular ("match" type) entries do indeed have a patient.

**Comment by jmandel** [comment]
(I see the same resource type filter on the field check feature, so the dame logic should apply ... but I'm observing what appear to be spurious errors about missing "patient" references. In particular, it's hard to interpret these errors because there's no context in the error report about *which* resource has this problem.)
