### ISSUE TITLE
Add support for STU3

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#118]
We'll want a Test Suite that can support FHIR STU3, especially for http://hl7.org/fhir/explanationofbenefit.html and http://hl7.org/fhir/claim.html (payor data)

**Comment by jmandel** [comment]
Could just be a fork of our existing test-suite

**Comment by jmandel** [comment]
I have some preliminary work; my TODO is to push the experimental branch to github.

**Comment by jmandel** [comment]
I've pushed https://github.com/sync-for-science/test-suite/tree/stu3 -- this is ready to test against CMS.

**Comment by jmandel** [comment]
@mtmcduffie  you can try the test suite via:

```
git clone https://github.com/sync-for-science/test-suite
cd test-suite
git checkout stu3
docker build -t tests .

docker run -v $(pwd):/usr/src/app --rm -it \
   -e FLASK_DEBUG=1 -e BASE_URL=http://tests.dev.syncfor.science:9003 \
   -p 5000:5000 \
    tests
```

then open a browser to http://localhost:5000 and choose CMS. (It won't get very far currently -- @aviars is aware of a couple of TODOs including, first step: making `/metadata` work)

**Comment by mtmcduffie** [comment]
Thinking through this.. would it be excessive for the reference-stack-docker to have multiple versions of the API Server and Tasks, one for DSTU2 and STU3? Or we could do different branches, repos..

**Comment by jmandel** [comment]
When you say "multiple versions" do you mean multiple repositories? I don't
see anyone solution that I love, but creating "-dstu2" and "stu3"
repositories is at least exploit and non-surprising.

**Comment by jmandel** [comment]
@mtmcduffie  https://dev.bluebutton.cms.fhirservice.net/protected/bluebutton/fhir/v1/metadata now works, so I think we're ready to start testing. We may not get *very* far, but we'll learn something. Can you pick this up next week?

**Comment by mtmcduffie** [comment]
Will do!

**Comment by mtmcduffie** [comment]
I've got a start to this by;

- Forking the sample patients to https://github.com/sync-for-science/sample-patients/tree/stu3 and changing some things around to get STU3 compliance.
- Added code and submodule to the reference-tasks folder in the reference-stack so that we can load STU3 patients.
- Added a new Dockerfile for FHIR 2.5 (STU3) - https://github.com/sync-for-science/reference-stack-docker/tree/feature/stu3/docker-builds/reference-api-stu3
- Added a new service to the reference-stack Dockerfile to be the SMART STU3 endpoint (Only requires config change for URL to point to new FHIR STU3)

I ran the tests against this new setup and most of them ran just about as well as they had against the STU2 setup.

Next I'll get a test-suite STU3 version running in the reference stack and work on getting that deployed, and then start iterating through bugs in the test-suite caused by the upgrade.

**Comment by jmandel** [comment]
updating the sample patients to STU3 might be painful / slow. It may be better to start with  https://github.com/smart-on-fhir/sample-patients-stu3 and use a prefix (--id-prefix "smart") to keep HAPI happy. The only thing you might want to add back is the security tags...

**Comment by mtmcduffie** [comment]
I'm going to tentatively call this one done.
