### ISSUE TITLE
No sample data for http://syncfor.science/api-calls/

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#121]
Aside from `Patient` endpoint, the test API calls are returning 0 results. The issue isn't actually a lack of underlying data, since the test suite shows data present.

**Comment by mtmcduffie** [comment]
Background - the problem was that some security was still being applied to the requests going through the proxy "open-fhir" endpoint. I thought it best that if we want to maintain a completely open endpoint we needed to fully separate the logic for unprotected and protected requests. Added an environmental trigger to enable the "open-fhir" endpoint.

**Comment by jmandel** [comment]
This looks good! A few small comments and I think it's ready to merge. Thanks @mtmcduffie.

**Comment by mtmcduffie** [comment]
Finally got around to pushing this out. Looks to have fixed all but a couple of the examples. I am going to create a new ticket to diagnose those other few because I think it may be a different problem.
