### ISSUE TITLE
Not allowed to query for "code" parameter through open-fhir

### ISSUE THREAD

**Issue by mtmcduffie** [sync-for-science/tracking#177]
This may be by design or limitation of FHIR server.

curl "https://portal.demo.syncfor.science/api/open-fhir/Observation?patient=smart-1288992&code=72166-2"

**Comment by jmandel** [comment]
By design. Our server is designed to support only the API calls described in the S4S guide, for MU Common Clinical Data Set. It's overly strict because we want developers to know exactly which calls are going to be consistently available.

For smoking status, use a category parameter: GET /api/open-fhir/Observation?category=social-history&patient=smart-1288992

**Comment by jmandel** [comment]
On review and after discussion with Alan Viars, Argonaut recommends the `code=` parameter as the way to implement Smoking Status category for the Common Clinical Data Set. We should figure out whether the current vendor implementations which pass our current test suite are also able to handle  the "&code=72166-2" query. If so, we should update our documentation to align with Argonaut.
