### ISSUE TITLE
Create a scaffold "research app" that designers can easily experiment with

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#65]
We want to make it easy to decouple design from technical backend, as a step toward building out a more powerful UX for the research app. Might start by cloning our existing research app and breaking the frontend apart from the backend, and having them talk via Ajax API. This will allow a frontend developer to build out features more easily. 

Details of how to accomplish this separation are... TBD. We can discuss here.

**Comment by jmandel** [comment]
- API feature: expose token to trusted backend.

**Comment by jmandel** [comment]
One possible separation:

### S4S UX (static web app, talks to Approver API)
- takes user through sign-in, provider search, and approval process

### S4S Approver Backend
- might never see any FHIR resources
- either exposes Access tokens to the synchronizer, _or_ it pushes them to the synchronizer

### S4S Synchronizer Backend (data fetch, cron job; talks to Approver API using a to get tokens)
- handles all protected health information (FHIR resources)
- Exposes a simple resource fetch API of some kind

---

TODO
- [ ] Swagger definition (or one-page writeup of APIs) -- good for internal discussion **and** hand-off / external communicaiton, or even driving an actual implementation

**Comment by erikwiffin** [comment]
https://gist.github.com/erikwiffin/2e9a97c87b5905e81b5462020ff08fcc

Not sure the best/easiest way to share swagger definitions, but this is a rough first pass at what I had in mind. http://editor.swagger.io/ is a pretty easy way to see them in action.

**Comment by jmandel** [comment]
Cool! This is a great start.

Could you document who would be expected to call each method, and what sort of authentication would be required? For example, if the "start-authorization" call is coming from the browser, then we went) want to ensure that "participant_id" was a valid id for this session, to prevent tampering. In other words, it implies that the API server needs some way to track sessions and know which participant is signed in. Could be a cookie based session, or an OAuth token,  or...  (Or perhaps you see this as a backend API call that the browser wouldn't touch directly  -- in which case this is fine, but the "UI" layer will need its own backend to talk to the authorizer in a secure way.) 
- Who turns refresh tokens into access tokens? 
- Should we try to enforce a stricter separation so the synchronizer holds the OAuth secrets and access tokens, and the authorizer can remain minimally privileged? 
- Does the synchronizer also operate on a clock (cron) or only when pinged? 
- Why does the authorizer use URLs like /participant/{participant_id}/ while the synchronizes uses "participant_id" as a (required) query parameter? 
- why return an intermediate "authorization" object from /participant/{participant_id}/authorizations instead of a responde that includes tokens+other pertinent details  directly? 
- How does the synchronizer learn the FHIR base URL it should be talking to for each authorization?

**Comment by erikwiffin** [comment]
I've set up a copy of our own swagger UI so you don't have to paste things into the swagger website. Haven't updated any documentation yet, but wanted to answer your questions.

> Who turns refresh tokens into access tokens?

My intention was that http://dev.syncfor.science:8000/?url=/authorization-api.yaml#!/Providers/post_providers_provider_id_store_authorization would convert authorization codes into refresh tokens, and then http://dev.syncfor.science:8000/?url=/authorization-api.yaml#!/Participants/get_participant_participant_id_authorizations_authorization_id_token would provide access tokens.

> Should we try to enforce a stricter separation so the synchronizer holds the OAuth secrets and access tokens, and the authorizer can remain minimally privileged?

My expectation was that the synchronizer wouldn't know _any_ secret information, other than obviously, FHIR resources.

> Does the synchronizer also operate on a clock (cron) or only when pinged?

The synchronizer can run on a clock, my thinking was that the easiest way to add one would be to set up a cron script that hits the http://dev.syncfor.science:8000/?url=/synchronizer-api.yaml#!/default/post_resources_synchronize endpoint.

> Why does the authorizer use URLs like /participant/{participant_id}/ while the synchronizes uses "participant_id" as a (required) query parameter?

The authorization backend was pretty easy to model in a REST-like fashion. `/participant` (should be **participants**, oops) would (theoretically) list participants, `/participant/{participant_id}` returns a single entry, `/participant/{participant_id}/authorizations` lists the authorizations for that entry. The synchronizer didn't fit that model quite as nicely. `/resources` would (theoretically) list all resources, `/resources/{resource_id}` would (theoretically) return a single resource entry. So `/resources?participant_id={participant_id}` filters the master list by participant.

> why return an intermediate "authorization" object

The idea was that the UI would call the `/participant/{participant_id}/authorizations` endpoint to get a list of authorizations it had made. It would then tell the synchronizer to fetch resources, and the Synchronizer would hit `/participant/{participant_id}/authorizations/{authorization_id}/token` in order to get valid access tokens to query resources. Depending on the expiration times, it's possible that if it queried all the access tokens at once, by the time it had finished sync-ing one authorization, the next access token would have expired.

> How does the synchronizer learn the FHIR base URL it should be talking to for each authorization?

That's a good question. Do you think it makes sense to return that at the `/token` endpoint?

**Comment by jmandel** [comment]
Nice! FWIW we can also point the UI right into your gist (probaly time to make a repo for this so I can propose changes too ;-)) [like this](http://dev.syncfor.science:8000/?url=https://gist.githubusercontent.com/erikwiffin/2e9a97c87b5905e81b5462020ff08fcc/raw/90184f04a9f4c290aa6cfc45a92e7a79d60fd628/authorization-api.yaml).

I'm still trying to get a sense of how security works. In a real-world deployment, is the static web app talking directly to the authorizer? to the synchronizer? If so, how are these calls authenticated? Which components need to know about user accounts? I think that's the biggest gap right now, and I see two general ways to resolve:
1. Declare the existence of yet another backend component, which doesn't expose any kind of documented API, but which handles user sign-in and account management (any real system would need this, anyway, so it's not _really_ like adding a new component), and has system-level access to certain endpoints within the authorizer and the synchronizer (i.e. it's trusted for operations like "POST /providers/{provider_id}/begin-authorization" and "POST /providers/{provider_id}/store-authorization" and "GET /participant/{participant_id}/authorizations").
2. Declare that the static web app needs to use a standard like OpenID Connect to do SSO, and then passes back an ID token to the authorizer in exchange for a narrowly-scoped, participant-specific access token. 

Between these, (2) is more explicit and puts less trust in the web client, but it assume a lot more about how the authorizer + synchronizer need to work. I think I prefer (1).

---

More thoughts:

> > why return an intermediate "authorization" object
> 
> Depending on the expiration times, it's possible that if it queried all the access tokens at once, by the time it had finished sync-ing one authorization, the next access token would have expired.

That's a great point! Some of these may be ~5min expiration periods.

---

> > How does the synchronizer learn the FHIR base URL it should be talking to for each authorization?
> 
> That's a good question. Do you think it makes sense to return that at the /token endpoint?

Sure -- or more generally: any time we have a token, we'll want to ensure we know the participant, provider, and FHIR API endpoint. We could model the FHIR API endpoint as a property of the practitioner.

> My expectation was that the synchronizer wouldn't know any secret information, other than obviously, FHIR resources.

Indeed -- and this makes sense. But given that FHIR resources are already "sensitive information" (PHI), I'm trying to figure out if we can/should push the OAuth secrets farther inside the secure environment. This relates to the question about auth that I asked at to the top of this comment; probably best to figure that out first.

> The synchronizer can run on a clock, my thinking was that the easiest way to add one would be to set up a cron script that hits the http://dev.syncfor.science:8000/?url=/synchronizer-api.yaml#!/default/post_resources_synchronize endpoint.

I'm not sure this is quite so easy, because the cron job would have to repeat this call for _every participant_ all the time. If we generalized the API call to support something like "sync everything", that could work. Or the cron job would be quite sophisticated and need access to the participant db, stats, etc -- at which point we probably don't gain much by running it through cron. (Don't get me wrong, I think having a "sync Josh's data _now_" feature is very helpful. I just think we need something additional to handle the predictable background demand.)

**Comment by erikwiffin** [comment]
I branched off of the existing reference-research-app for now. https://github.com/sync-for-science/reference-research-app/tree/docs
- http://dev.syncfor.science:8000/?url=https://raw.githubusercontent.com/sync-for-science/reference-research-app/docs/authorization-api.yaml
- https://raw.githubusercontent.com/sync-for-science/reference-research-app/docs/synchronizer-api.yaml

---

I hadn't put much thought into security, but generally I think I was assuming something like (1). Everyone is going to have their own security implementation, so hopefully they can just extend it to this.

My expectation was that the static web app would be talking to both of these APIs as needed, and that the synchronizer would request access tokens from the authorizer.

---

I've updated the /token endpoint.

> But given that FHIR resources are already "sensitive information" (PHI), I'm trying to figure out if we can/should push the OAuth secrets farther inside the secure environment.

My thinking is more based on separation of concerns than in security, I don't think the synchronizer needs to know anything about oauth credentials other than "I can use a bearer token to access resources". If we gave it the oauth client_id/client_secret, it would still need to provide those to the authorizer so that the authorizer could do it's job, so at that point, they would become "compromised". Might as just have them there to start with.

> the cron job would have to repeat this call for every participant all the time.

Good point. What do you think about documenting that the synchronizer needs to establish some internal mechanism for synchronizing all the participants/resources? I don't think we need to be prescriptive here since different synchronizers will probably have different needs (1,000,000 participants vs 1 participant will definitely use different scheduling systems) and the point of this is to define the public API.

If we do that, the existing `/resources/synchronize` endpoint becomes a lot less necessary, and I'd be tempted to take it out, because YAGNI, but it also seems like a really useful thing to have. If `/resources/synchronize`, the synchronizer API ends up looking an awful lot like a FHIR server. What do you think about saying "implement the S4S API" instead of having a single `/resources` endpoint just dumps out a giant list of resources?

**Comment by jmandel** [comment]
If we assume (1), that solves a bunch of problems. But also note that it means the _static_ component of the web app wouldn't be talking directly to the Authorizer or Synchronizer. We'd need to provide a backend component for the UX server to keep the API keys for talking to those components.

Separation of concerns between Authorizer and Synchronizer: this works (and likely these would be deployed side by side within a given organization). 

Yes, I'm very happy leaving the algorithm for the Synchronizer "below the abstraction barrier". Our reference  implementation can be pretty simple but should be able to scale to 5k participants (to cover possible size of a pilot program). 

---

I think the "start-authorization" API call should return an authorization_id and a redirect  URL (or something like that). Because we want to be able to call if from outsiders of the browser and _learn_ the authorize url without directly _going_ there. Does that make sense? And then the store-authorization can take a id as a path parameter to avoid mixups.

**Comment by erikwiffin** [comment]
> the static component of the web app wouldn't be talking directly to the Authorizer or Synchronizer.

Is there any value in make an authentication prescription so that we don't lose that feature?

> I think the "start-authorization" API call should return an authorization_id and a redirect URL (or something like that).

My thinking with the 302 was that if the UI is using the API directly, it can just follow the redirect, and if it isn't, then it can make some kind of `follow_redirects = False` query against the API and extract the URL from the Location header. I also don't think using the authorization_id as a path parameter would work, since (at least with most of the vendors so far) there tends to be single valid `redirect_uri` for each OAuth client, and we can't just stick an authorize_id in that.

**Comment by jmandel** [comment]
I think I didn't explain this very well - let's plan to discuss tomorrow :)

**Comment by jmandel** [comment]
To be clear, I just meant adding a path parameter to the _store-authorization_ endpoint, like `/authorizations/123/store`. 

I think the issue with redirection is knowing _who_ is allowed to call "start-authorization" -- I'm assuming this must be an authenticated call, and that means it won't come straight from the browser, in which case a 302 response feels strange. Better to return something like 

``` json
{
  "authorization_id" : "123",
 " authorize_uri": "full uri with all parameters baked in", 
  "//state?": "abc"
} 
```

Now the question here is how will `state` be verified upon completion? A well written UI would ensure that the state matched upon receiving the post-OAuth redirect. It's not good enough to leave this job to the Authorizer,  because it's essential to confirm that the code is arriving in the same browser session that the request originated from. And the Authorizer won't have any insight into this.

**Comment by jmandel** [comment]
Some additional thoughts for discussion:

In Authorizer:

### Create authorization:

```
POST /authorization
{
  provider: 123,
  participant: 456
}

-->
{
  provider: 123,
  participant: 456,
  authorize_uri: "https://..?state=&client_id=...",
  state: "onetime-thing-123"
}
```

### Finish authorization

```
POST /authorization/abc123/code

{
  code: "onetime-abc",
  state: "onetime-thing-123"
}
--> 200 OK
```

---

In Synchronizer:

## Get overview for display

```
GET /participant/123/summary

--> [{
    provider: "Dr. Jones",
    provider_id: "123",
    counts: {
        MedicationOrder: 6,
        Immunization: 4,
        Observation: 310
    }
}]
```

## Get resources of a type from a particular provider

```
GET /participant/456/provider/123/Observation
--> FHIR payload
```

## Get all resources from a provider

```
GET /participant/456/provider/123/$everything
--> FHIR payload
```

**Comment by jmandel** [comment]
Also to be determined: where do new "participant ids" come from? The Authorizer probably needs an API endpoint to create them. Would consider something like `POST /Participant` with a FHIR Patient resource as payload. (Overall we should figure out whether/how to align these APIs with FHIR resources; or at least whether to adhere to FHIR conventions like singular nouns rather than plural.)

**Comment by erikwiffin** [comment]
Updated swagger definition. http://dev.syncfor.science:8000/?url=https://raw.githubusercontent.com/sync-for-science/reference-research-app/docs/synchronizer-api.yml Doesn't cover everything from our conversation, but does formalize [thoughts.md](https://gist.github.com/jmandel/0e60c2949df16e9e19735c7ad175ee1d).
