### ISSUE TITLE
Implement a token service to support revocation checking 

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#8]
We will need a way for patients to revoke access to an app.  Effectively this means that after a patient revokes access, the option no longer be able to request their data and less they reauthorize.

Our server currently uses signed Json web tokens as access tokens, and they are not currently revocable. 

Rather than simply issuing signed statements, our authorization server should be recording every access token and refresh token that it issues via some kind of  service. The service API would be something like:

```
TokenService.generate(params) 
```

Where parameters include: grant, scope

```
TokenService.revoke(token) 
```

Where "token" is the full access token string. 

```
TokenService.verify(token) 
```

Where "token" is a full access token string, and the response is a full token details object (expiration date, grant, context, scope, etc). 

---

A basic 'None' TokenService would continue using JWTs and would not support revocation. And a more advanced service would support database or memory's backed token storage and look-up, so revocation would be available.

**Comment by erikwiffin** [comment]
If you get the chance, could you take a look at https://github.com/smart-on-fhir/smart-stub/compare/refactor...FLEEThealth:feature/token-service?expand=1 for me?

I've made a first pass at a None implementation of the token service that just maintains current behavior. I'm a little fuzzy on what logic needs to live where, so my instinct was to wrap up any calls to `jwt.sign` and `jwt.verify` inside the token service. I saw three main uses of that method:
- generating 5m temporary tokens to enable other oauth methods
- generating empty tokens as placeholders
- and finally the actual authorization generation

It seems to me like we should get attempt to refactor away the first two, or they don't belong in the TokenService, and I should stop thinking of it as a wrapper for `jwt.sign`.

Then answer to that question will probably answer this one too, but is the launch token call to `jwt.decode` something that should also be in the TokenService?

**Comment by jmandel** [comment]
The bullet list here helps! I think you're right that it makes sense to think about a service for "authorization tokens" (your third bullet) as distinct from as service for "authorization codes" (your first bullet point). We probably need services for both. But first we need to define the inputs/outputs.

### For authorization codes
- `generate`: inputs are https://github.com/smart-on-fhir/smart-stub/blob/refactor/src/smart/auth.js#L46-L55 and the output is a token string
- `verify`: input is a token string, and output is whatever got passed to `generate`

### For authorization tokens
- `generate`: inputs are a grant (https://github.com/smart-on-fhir/smart-stub/blob/refactor/src/smart/auth.js#L116-L124) and claims (https://github.com/smart-on-fhir/smart-stub/blob/refactor/src/smart/auth.js#L149-L155), and the output is a token string
- `verify`: input is a token string, and output is whatever got passed to `generate`

### Empty placeholders?

Remind me where these are used.

**Comment by erikwiffin** [comment]
Looks like empty placeholders are only being used in the /authorize endpoint for creating an initial launchJwt: https://github.com/FLEEThealth/smart-stub/blob/refactor/src/smart/auth.js#L90. I thought I saw more of them because auth.js calls out to oauth-helpers.js and I had to make changes more than once.

Since codes and tokens are so similar, would it make more sense to have one service with two methods, `generateAuthorizationCode` and `generateAuthorizationToken`? They can both use the same verify method.

Maybe this will help me distinguish their purpose, when I implement some kind of DB backed system, would codes and tokens be stored there? or just tokens?

**Comment by jmandel** [comment]
Ah, so the empty token was just a trick to deal with the case where launch token is missing. But that does raise the point that in addition to OAuth authorization codes and OAuth tokens (access + refresh), we also have "SMART launch tokens", which could be managed explicitly too. We don't need SMART launch tokens in S4S, so we can leave it aside for now, as long as we don't break what's there.

Great framework for thinking about the distinction between codes + tokens. You _could_ store them both in a db the same way, but it's also totally reasonable for "codes" to live only in-memory (since they're short-lived) while access tokens hit the db. Also when it comes to patients seeing "what apps have access to my data", access tokens and refresh tokens are the relevant records to display here; authorization codes are too short-lived to matter.

**Comment by jmandel** [comment]
When it comes to https://github.com/smart-on-fhir/smart-stub/compare/refactor...FLEEThealth:feature/token-service?expand=1#diff-b4f2d915146072cda9ac5ca70ad15281R18 -- the refresh token also needs be verifiable through this same API (i.e. in the db-backed version, the refresh token will need to be independently stored in the db).

**Comment by erikwiffin** [comment]
Okay, I think that gives me some context to go a bit further. At the very least I understand what to do with tokens, and can figure out where codes fit in as I go.

You mentioned before that you were imagining a full database that these services would write to, instead of just sqlite. I'm not opposed to that, and in this situation, I think redis would be a really great fit since it natively supports expiring records. Should I be attempting to run redis inside the api-gateway container, or should it get its own contain that anything can talk to over port 9003?

**Comment by jmandel** [comment]
To be clear: I have nothing against sqlite! A single .sqlite db file baked into the image would be okay. We could mount that .sqlite file as a volume in production, for persistence.

That said, if you do want to use an external db (say, postgresql or redis) it should run as its own "service" in the docker-compose stack (and that service, in turn, should store its data in a volume for persistence).

**Comment by erikwiffin** [comment]
I've pushed up another commit to my feature branch that includes a Sqlite service https://github.com/FLEEThealth/smart-stub/commit/e8c2599d2ac52f0491b1367b41fefe5c57612d89. I still think redis is a good fit here, but sqlite is easier to get up and running so we can swap out the backend once we've established the token service a little bit more.

I'm going to clean up my code a lot, but I wanted to check-in and make sure I wasn't missing anything obvious about revoking tokens. All the sqlite functionality is present, and I've got it falling back to the None implementation to actually generate the JWTs.

I still need to add a POST endpoint to `src/smart/auth.js` for `/revoke`. It will expect a `token` param, and will use the `tokenService.revoke` method to revoke it. Should I be copying the validation in `/token` so that it's not possible to revoke arbitrary tokens?

**Comment by jmandel** [comment]
Thanks! I'll review shortly. For the revoke endpoint, I suppose it is fair to argue that if anyone who  knows the value of a token should be able to revoke it. We can probably do without protection for the moment.

**Comment by jmandel** [comment]
Ok, a few notes

I think you get good leverage from building on the "naive" methods.

We should make "generate" methods  return a promise rather than a  value. This allows us to ensure db operations complete before code flow continues. 

In cleanup, be careful to resolve returned promises only after the necessary db operations have successfully completed (i.e. you need callbacks in your sqlite `run` invocations, and promise resolution inside successful callbacks, or rejection on errors). 

If we want to enforce a 1:1 relation between refresh tokens and access tokens, that's fine; it effective means that using a refresh token expires any previous access tokens.

**Comment by erikwiffin** [comment]
Thanks for that feedback.

Will do on promises. I think I'll probably switch to this library too https://www.npmjs.com/package/q-sqlite3, so that I'm not manually wrapping each db call in a promise myself.

I think I'll probably pull refresh tokens into their own table. I'd be surprised if we don't end up wanting to do that later anyways.
